version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - career-coach
    restart: unless-stopped



networks:
  career-coach: