# Namespace: career-coach
kind: Namespace
apiVersion: v1
metadata:
  name: career-coach

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: career-coach-deployment
  namespace: career-coach
spec:
  replicas: 2
  selector:
    matchLabels:
      app: career-coach
  template:
    metadata:
      name: career-coach-frontend-pod
      labels:
        app: career-coach
    spec:
      containers:
      - name: career-coach-frontend
        image: shubhankar24/ai-career-coach:sha-903183bdb90d4fc88b3587ca8c68f9e8686026ce
        # resources:      # Resource Quotas for limitation of CPU and Memory Usage
        #   requests:
        #     memory: "128Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "256Mi"
        #     cpu: "200m"
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
            secretKeyRef:
              name: career-coach-secret
              key: DATABASE_URL

          - name: CLERK_SECRET_KEY
            valueFrom:
            secretKeyRef:
              name: career-coach-secret
              key: CLERK_SECRET_KEY

          - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            valueFrom:
            secretKeyRef:
              name: career-coach-secret
              key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

          - name: GEMINI_API_KEY
            valueFrom:
            secretKeyRef:
              name: career-coach-secret
              key: GEMINI_API_KEY
          

